### ISSUE TITLE
I can't download the models!

### ISSUE THREAD

**Issue by mbgarcia89** [Chien-Hung/ImageRetrievalGUI#2]
I am unable to download the models in:

"Or you can download the trained checkpoints [cub200_checkpoint.pth.tar](https://drive.google.com/file/d/1Gem3-9mzutHbNtBVQS8yIi_DPOG0YV2S/view?usp=sharing) / [cars196_checkpoint.pth.tar](https://drive.google.com/file/d/1wvP3Engemk9RTwiE6cZJjjjonXLXscEA/view?usp=sharing)."

Can you help me or are they no longer available?

**Comment by Chien-Hung** [comment]
I update the checkpoint link. Please try again.

**Comment by mbgarcia89** [comment]
Thanks!
