### ISSUE TITLE
how to be referenced

### ISSUE THREAD

**Issue by mbgarcia89** [Chien-Hung/ImageRetrievalGUI#3]
Do you have any particular publication on which you base your image retrieval model?

**Comment by Chien-Hung** [comment]
This is a visualization project based on Deep-Metric-Learning model. I used [Deep-Metric-Learning-Baselines](https://github.com/Confusezius/Deep-Metric-Learning-Baselines) / [Revisiting_Deep_Metric_Learning_PyTorch](https://github.com/Confusezius/Revisiting_Deep_Metric_Learning_PyTorch) project training a model for demo, so maybe you can reference their publication.
